「ひとこと掲示板」リツイート機能＋いいね機能追加
RYU1030/quelcode-php pull request #5
Opened 2020-05-16 09:25 UTC by RYU1030

2020-05-18 13:31 UTC, RYU1030 commented
「掲示板課題」初回提出。

2020-05-19 04:02 UTC, choimake reviewed
動作に関しては良くできています。特に問題はありませんでした。

コードの書き方についていくつか修正して欲しい点がありますので、そちら対応お願いします。自分が編集、追加したファイルの範囲で構いません。
（元のソースが既に残念なので、色々難しいかもしれませんが対応お願いします。）

2020-05-19 04:02 UTC, choimake commented on html/php-challenge/delete.php
> +				// 論理削除
比較をする際には「==」ではなく「===」を使うようにしてください。
型を意識して、比較処理を実装するようにしましょう。

2020-05-19 04:02 UTC, choimake commented on html/php-challenge/delete.php
> +			$del->execute(array(
「retweeted_post_id」では単語と単語の間に「_」が入っているのに、「deleteflag」では入っていません。
命名規則は統一するようにしましょう。

2020-05-19 04:02 UTC, choimake commented on html/php-challenge/index.php
> +						?>
インデントが揃っていません。実装をする際は、インデントを揃えるようにしましょう。

2020-05-19 04:02 UTC, choimake commented on html/php-challenge/likes_do.php
> +    $liked_post_id,
インデントの大きさが揃っていません。
自分が編集したファイル全体の範囲で構いませんので、インデントのサイズを統一するようにしてください。

2020-05-19 07:31 UTC, RYU1030 commented on html/php-challenge/delete.php
> +				// 論理削除
上記、了解です。
修正致しました。

2020-05-19 07:31 UTC, RYU1030 commented on html/php-challenge/delete.php
> +			$del->execute(array(
命名規則を統一しました。

2020-05-19 07:32 UTC, RYU1030 commented on html/php-challenge/index.php
> +						?>
インデントの整列を行った後、php intellisense による整形を行いました。

2020-05-19 07:32 UTC, RYU1030 commented on html/php-challenge/likes_do.php
> +    $liked_post_id,
インデントサイズを統一しました。

2020-05-19 07:33 UTC, RYU1030 commented
ご指摘事項に対応いたしました。
ご確認のほど、よろしくお願い申し上げます。

2020-05-19 08:23 UTC, choimake reviewed
コメントしましたので確認お願いします。

2020-05-19 08:23 UTC, choimake commented on html/php-challenge/likes_do.php
> +  $liked_by = $_REQUEST['liked_by'];
index.phpのインデントサイズが4ですが、likesやretweetなどのインデントのサイズは2となっています。
ファイルごとにインデントサイズが異なっているのは、コードの可読性という観点で好ましく無いので、インデントサイズを統一してください。

※index.phpとlikes関連、retweet関連、delete関連だけ統一できていれば大丈夫です。

2020-05-19 08:23 UTC, choimake commented on html/php-challenge/index.php
> +//error_reporting(E_ALL);
処理のコメントアウトは残さないようにしましょう。不要なら消す、使うならコメントアウトを外してください。
必要なのか不要なのか、他の人からよくわからないコードは残さないようにする方が好ましいです。

これは前回の指摘漏れに当たる部分になります。申し訳ありません。

2020-05-19 09:06 UTC, RYU1030 commented on html/php-challenge/likes_do.php
> +  $liked_by = $_REQUEST['liked_by'];
index.php のインデントサイズが統一されるように、php intellisense を介さずに整列を行いました。

2020-05-19 09:06 UTC, RYU1030 commented on html/php-challenge/index.php
> +//error_reporting(E_ALL);
不要なコメントアウトを削除致しました。
ご指摘ありがとうございます。

2020-05-19 09:07 UTC, RYU1030 commented
不要なコメントの削除 + index.php のインデントサイズが統一されるように、php intellisense を介さずに整列を行いました。

2020-05-20 03:36 UTC, piasoratech commented on html/php-challenge/likes_do.php
> +  $liked_by = $_REQUEST['liked_by'];
delete関連にはdelete.phpも含まれるので、そちらも修正をお願いします。

2020-05-20 03:37 UTC, piasoratech requested changes
コメントしたので確認をお願いします。

2020-05-20 03:37 UTC, piasoratech commented on html/php-challenge/delete.php
>  <?php
ちょいまけさんの指摘にある「delete関連」はこのファイルも含まれるので、こちらもインデントをそろえるようお願いします。

2020-05-20 03:46 UTC, RYU1030 commented on html/php-challenge/likes_do.php
> +  $liked_by = $_REQUEST['liked_by'];
delete.php を再度整形致しました。

2020-05-20 03:47 UTC, RYU1030 commented on html/php-challenge/delete.php
>  <?php
delete.php を再度整形致しました。

2020-05-20 05:18 UTC, piasoratech commented on html/php-challenge/delete.php
>  <?php
すいません。私の指摘の仕方が悪かったですね。
インデントサイズの話をしていました。こちらのファイルのインデントサイズは4になっているので、index.php等と揃えるためにもインデントサイズを2にするようお願いします。

2020-05-20 05:18 UTC, piasoratech requested changes
前回の指摘内容に返信する形でコメントしたので確認をお願いします。

2020-05-20 05:33 UTC, RYU1030 commented
ded5e8e　にて、インデントサイズを調整いたしました。

2020-05-20 06:35 UTC, piasoratech approved these changes
よいかと！

2020-05-20 06:45 UTC, merged